#!/usr/bin/env python
import os

__all__ = ["Env"]

__version__ = "0.1"

DEBUG = os.getenv("DEBUG", True)

GO_REPLAY_PATH = os.getenv("GO_REPLAY_PATH", "/usr/local/bin")
GO_REPLAY_FILENAME = "goreplay"
GO_REPLAY_FULLPATH = os.path.join(GO_REPLAY_PATH, GO_REPLAY_FILENAME)

if DEBUG:
    print("GO_REPLAY_PATH: %s" % GO_REPLAY_PATH)
    print("GO_REPLAY_FILENAME: %s" % GO_REPLAY_FILENAME)
    print("GO_REPLAY_FULLPATH: %s" % GO_REPLAY_FULLPATH)

CONFIGURATION_PATH = os.getenv("CONFIGURATION_PATH", "/etc/cloner")
CONFIGURATION_CLONER_FILENAME = "cloner.json"
CONFIGURATION_CLONER_FULLPATH = os.path.join(CONFIGURATION_PATH, CONFIGURATION_CLONER_FILENAME)
CONFIGURATION_CLONER_SERVICE_FILENAME = "config.json"
CONFIGURATION_CLONER_SERVICE_FULLPATH = os.path.join(CONFIGURATION_PATH, CONFIGURATION_CLONER_SERVICE_FILENAME)

if DEBUG:
    print("CONFIGURATION_PATH: %s" % CONFIGURATION_PATH)
    print("CONFIGURATION_CLONER_FILENAME: %s" % CONFIGURATION_CLONER_FILENAME)
    print("CONFIGURATION_CLONER_FULLPATH: %s" % CONFIGURATION_CLONER_FULLPATH)
    print("CONFIGURATION_CLONER_SERVICE_FILENAME: %s" % CONFIGURATION_CLONER_SERVICE_FILENAME)
    print("CONFIGURATION_CLONER_SERVICE_FULLPATH: %s" % CONFIGURATION_CLONER_SERVICE_FULLPATH)
